accountprofile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list',
         views.ListAccountProfile.as_view(),
         name='list_account_profile'),
    path('detail/<int:pk>',
         views.DetailAccountProfile.as_view(),
         name='detail_account_profile'),
    path('update/<slug:factory>',
         views.CreateUpdateController.as_view(),
         name='update_account'),
    path('update/<slug:factory>/<int:pk>',
         views.CreateUpdateController.as_view(),
         name='update_account'),
    path('update/<slug:factory>/<slug:del>',
         views.CreateUpdateController.as_view(),
         name='update_account'),
    path('update/<slug:factory>/<slug:new_transfer>/<int:account>',
         views.CreateUpdateController.as_view(),
         name='update_account'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Main.as_view(), name='main')
]

oshstudy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('main.urls')),
    path('accountprofile/', include('accountprofile.urls')),
    path('company/', include('company.urls')),
    path('contract/', include('contract.urls')),
    path('knowledge/', include('knowledge.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('study/', include('study.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('comments/', include('django_comments_xtd.urls')),
    path('quiz/', include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountprofile/models.py
from django.db import models
from  company.models import Division, Position, Company
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.


class AccountProfile(models.Model):
    MIDDLE_EDUCATION = 'MD'
    SPECIAL_EDUCATION = 'SP'
    HIGHER_EDUCATION = 'HI'
    LEVEL_EDUCATION = [
        (MIDDLE_EDUCATION, 'Среднее образование'),
        (SPECIAL_EDUCATION, 'Среднеспециальное образование'),
        (HIGHER_EDUCATION, 'Высшее образование'),
    ]
    name = models.CharField(verbose_name='Имя', max_length=100)
    second = models.CharField(verbose_name='Фамилия', max_length=100)
    middle = models.CharField(verbose_name='Отчество', max_length=100)
    education = models.CharField(verbose_name='Образование', max_length=100, choices=LEVEL_EDUCATION,)
    birthday = models.DateField(verbose_name='День рождения', )
    snils = models.CharField(verbose_name='СНИЛС', max_length=100)
    create = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    update = models.DateTimeField(verbose_name='Обнавлен', auto_now=True)
    foto = models.ImageField(verbose_name='Аватар', upload_to='account_photo')
    education_file = models.FileField(verbose_name='Документ об образовании', max_length=100)

    class Meta:
        verbose_name_plural = "Профиль"

    def __str__(self):
        return "{0} {1} {2}".format(self.second, self.name,  self.middle)


class Present(models.Model):

    account_profile = models.ForeignKey(AccountProfile, on_delete=models.CASCADE, related_name='present')
    company = models.ForeignKey(Company, models.SET_NULL, blank=True, null=True, verbose_name='Компания')
    division = models.ForeignKey(Division, models.SET_NULL, blank=True, null=True, verbose_name='Подразделение')
    position = models.ForeignKey(Position, models.SET_NULL, blank=True, null=True, related_name='children', verbose_name='Должность')
    event = models.CharField(max_length=10, verbose_name='Событие', default=None)
    active_event = models.IntegerField(verbose_name='Активная позиция', default=0)
    date_event = models.DateField(verbose_name='Дата события',  default=None)

    class Meta:
        verbose_name_plural = "Форма собственности"
        indexes = [
            models.Index(fields=['company', 'account_profile'])
        ]

    def __str__(self):
        return (self.account_profile.name)


class History(models.Model):
    account_profile = models.ForeignKey(AccountProfile, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, models.SET_NULL, blank=True, null=True, verbose_name='Компания')
    division = models.CharField(verbose_name='Подразделение', max_length=255)
    position = models.CharField(verbose_name='Должность', max_length=255)
    event = models.CharField(max_length=10, verbose_name='Событие', default=None)
    date_event = models.DateField(verbose_name='Дата события', default=None)
    present = models.ForeignKey(Present, verbose_name='Подразделение', on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        verbose_name_plural = "история"
        indexes = [
            models.Index(fields=['account_profile'])
        ]

    # def __str__(self):
    #     return (self.account_profile)

accountprofile/forms.py
from django import forms
from bootstrap_datepicker_plus import DatePickerInput
from company.forms import Division
from mptt.forms import TreeNodeChoiceField
from company.models import Position
from accountprofile.models import Present


class TransferAccountForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'id' in args:
            queryset = Present.objects.filter(id=args[0]['id']).values()
            self.data = {**queryset[0]}
            self.fields['date_event'].label = 'Дата перевода'

    id = forms.IntegerField(
        label='id',
        required=False,
        widget=forms.HiddenInput())

    account_profile_id = forms.IntegerField(
        label='id',
        required=False,
        widget=forms.HiddenInput())

    date_event = forms.DateField(
        label='Дата приема',
        help_text='Укажите дату трудового договора',
        widget=DatePickerInput(
            format='%d.%m.%Y',
        )
    )

    division_id = TreeNodeChoiceField(
        help_text='Для получения должностей сначало выберите подразделение',
        queryset=Division.objects.all(),
        level_indicator='_____',
        label="Подразделение",
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )

    # position_id = forms.ModelChoiceField(
    #     # queryset=Position.objects.all(),
    #     help_text='Обязательно укажите должность работника',
    #     label=u"Должность работника",
    #     # widget=s2forms.ModelSelect2Widget(
    #     #     empty_label='Empty',
    #     #     model=Position,
    #     #     max_results=10,
    #     #     search_fields=['name__icontains'],
    #     #     dependent_fields={'division_id': 'division_id'},
    #     #     attrs={
    #     #         'data-minimum-input-length': 0,
    #     #         # 'data-placeholder': '------',
    #     #         # 'style': 'width: 50%'},
    #     #         'class': 'form-control',
    #     #     }
    #     # )
    # )


class EditAccountForm(forms.Form):
    MIDDLE_EDUCATION = 'MD'
    SPECIAL_EDUCATION = 'SP'
    HIGHER_EDUCATION = 'HI'
    LEVEL_EDUCATION = [
        (MIDDLE_EDUCATION, 'Среднее образование'),
        (SPECIAL_EDUCATION, 'Среднеспециальное образование'),
        (HIGHER_EDUCATION, 'Высшее образование'),
    ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    id = forms.IntegerField(
        label='id',
        required=False,
        widget=forms.HiddenInput())

    name = forms.CharField(
        label='Имя',
        max_length=100,
        help_text='Введите имя',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            })
    )

    second = forms.CharField(
        label='Фамилия',
        max_length=100,
        help_text='Введите фамилию',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            })
    )

    middle = forms.CharField(
        label='Отчество',
        max_length=100,
        help_text='Введите отчество',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            })
    )

    education = forms.ChoiceField(
        choices=LEVEL_EDUCATION,
        label='Введите уровне образования',
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            })
    )

    birthday = forms.DateField(
        label='День рождения',
        help_text='Введите дату рождения',
        widget=DatePickerInput(
            format='%d.%m.%Y',
        )
    )

    snils = forms.CharField(
        label='СНИЛС',
        max_length=100,
        help_text='Введите СНИЛС работника',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id': 'snils'
            })
    )


class CreateAccountForm(EditAccountForm, TransferAccountForm):
    pass


class FireAccountForm(forms.Form):

    id = forms.IntegerField(
        label='id',
        required=False,
        widget=forms.HiddenInput())


class AccountFotoForm(forms.Form):
    foto = forms.ImageField(
        label='Фото сотрудника',
        help_text='Имя', )


class DiplomaFileForm(forms.Form):
    education_file = forms.FileField(
        label='Документ об образовании',
        max_length=100,
        help_text='Имя', )


class PhotoForm(forms.Form):
    id = forms.IntegerField(label='id', required=False, widget=forms.HiddenInput())
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    foto = forms.ImageField(label='Фото сотрудника')

accountprofile/views.py
from django.shortcuts import render
from django.views.generic.base import View
from accountprofile.factory import *
from django.urls import reverse
from django.http import HttpResponseRedirect
from system.mixins.permission import PermissionGroupMixin
from .tables import AccountProfileTable
from django_tables2 import RequestConfig
from system.common.filters import AccountProfileFilter

# Create your views here.


class BaseController:
    _class_name = ''

    def __init__(self, *args, **kwargs):
        self.data_for_form = False
        if self._class_name:
            self.configurator = Configurator(self._class_name)
        super().__init__(*args, **kwargs)

    def get_obj(self, request_data, kwargs=''):
        """request_data - это данные из request. Приходят из функции get класса (объекта)"""
        obj = self.configurator.get_object_group(request_data)
        """configurator - получаем из factory см. метод init"""
        if 'factory' in kwargs:
            """Проверяем есть ли метко для выбора фабрики. Передается через URL"""
            if kwargs['factory'] in obj.permission_list_of_factories:
                """permission_list_of_factories - перечень фабрик доступных для группы пользователей"""
                """представлен в файле этой группы папки accessview"""
                obj.select_form_factory(kwargs['factory'])
        return obj


class UserAccountProfile(PermissionGroupMixin, BaseController, View):
    permission_required = ['sch', 'admin', 'hse']

    def __init__(self, *args, **kwargs):
        self.configurator = Configurator(self.__class__.__name__)
        super().__init__(*args, **kwargs)


class ListAccountProfile(PermissionGroupMixin, BaseController, View):
    permission_required = ['sch', 'admin', 'hse']

    def __init__(self, *args, **kwargs):
        self._class_name = self.__class__.__name__
        super().__init__(*args, **kwargs)

    def get(self, request, **kwargs):
        obj = self.get_obj(request, **kwargs)
        account_profile = obj.get_account_profile_list(request.session['company_id'])
        table = AccountProfileTable(account_profile)
        RequestConfig(request).configure(table)
        table.paginate(page=request.GET.get("page", 1), per_page=20)
        return render(request, obj.template, {'table': table})


class DetailAccountProfile(PermissionGroupMixin, BaseController, View):
    permission_required = ['sch', 'admin', 'hse']

    def __init__(self, *args, **kwargs):
        self._class_name = self.__class__.__name__
        super().__init__(*args, **kwargs)

    def get(self, request, **kwargs):
        obj = self.get_obj(request, kwargs)
        return render(request, obj.template, {
            'profile': obj.get_detail_account_profile(request.session['company_id'], kwargs['pk']),
            'presents': obj.get_present(request.session['company_id'], kwargs['pk']),
            'histories': obj.get_history(kwargs['pk']),
        })


class CreateUpdateController(PermissionGroupMixin, BaseController, View):
    permission_required = ['sch', 'admin', 'hse']

    def __init__(self, *args, **kwargs):
        self.configurator = Configurator(self.__class__.__name__)
        super().__init__(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        obj = self.get_obj(request, kwargs)
        if 'pk' in kwargs:
            self.data_for_form = obj.chosen_form_factory.model.get_data(kwargs['pk'], request)
        form = obj.chosen_form_factory.form.get_form(self.data_for_form, kwargs)
        return render(request, obj.chosen_form_factory.template_form, {
            'form': form,
            'kwargs': kwargs,
            'account_data': self.data_for_form})

    def post(self, request, *args, **kwargs):
        obj = self.get_obj(request, kwargs)
        form = obj.chosen_form_factory.form.get_form(request.POST, request.FILES)
        if form.is_valid():
            if 'del' in kwargs:
                obj.chosen_form_factory.model.del_data(request, form.cleaned_data)
            else:
                obj.chosen_form_factory.model.make_save(request, form.cleaned_data)
            return HttpResponseRedirect(reverse(obj.chosen_form_factory.redirect_url))
        else:
            return render(request, obj.chosen_form_factory.template_form, {
                "form": form,
                'kwargs': kwargs})

templates/accountprofile/hse/detail_account_profile.html
{% extends 'adminlte/base.html' %}

{% block content %}
    {% for account in profile %}
        <div class="row">
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="box box-primary">
                    <div class="box-body box-profile">
                        {% if account.account_profile.foto %}
                            <a href="{% url 'update_account' 'photo' account.account_profile_id %}">
                                <img class="profile-user-img img-responsive img-circle"
                                     src="{{ MEDIA_URL }}{{ account.account_profile.foto }}" alt="Фото работника">
                            </a>

                        {% else %}
                            <a href="{% url 'update_account' 'photo' account.account_profile_id %}"
                               class="btn btn-default btn-block">Фото добавить</a>

                        {% endif %}
                        <h3 class="profile-username text-center">{{ account.account_profile }}</h3>
                        <ul class="list-group list-group-unbordered">
                            <li class="list-group-item">
                                <b>Личные данные</b>
                                <a href="{% url 'update_account' 'edit_account' account.account_profile.id %}"
                                   class="pull-right">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </li>
                            <li class="list-group-item">
                                <b>Перевод</b>
                                <a href="{% url 'update_account' 'transfer_account' 'new_transfer' account.account_profile.id %}"
                                   class="pull-right">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </li>
                        </ul>
                        <a href="{% url 'update_account' 'fire_account' account.account_profile.id %}" class="btn btn-danger btn-block"><b>УВОЛИТЬ</b></a>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->

                <!-- About Me Box -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Данные</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <strong><i class="fa fa-sitemap margin-r-5"></i> Текущее подразделение</strong>
                        <p class="text-muted">
                            {{ account.division }}
                        </p>
                        <hr>
                        <strong><i class="fa fa-group margin-r-5"></i> Текущая должность</strong>
                        <p class="text-muted">
                            {{ account.position }}
                        </p>
                        <hr>
                        <strong><i class="fa fa-graduation-cap margin-r-5"></i> Образование</strong>
                        <p class="text-muted">
                            {{ account.account_profile.get_education_display }}
                        </p>
                        <hr>
                        <strong><i class="fa fa-map-marker margin-r-5"></i> Рабочее место</strong>
                        <p class="text-muted">Malibu, California</p>
                        <hr>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#activity " data-toggle="tab" aria-expanded="true">События</a></li>
                        <li class=""><a href="#timeline" data-toggle="tab" aria-expanded="false">История</a></li>
                        <li class=""><a href="#settings" data-toggle="tab" aria-expanded="false">Настройки</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="activity">
                            <div class="alert alert-info alert-dismissible">
                                <h4><i class="icon fa fa-info"></i> Сообщение</h4>
                                У данного сотрудника нет активных событий.
                            </div>
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="timeline">
                            {% if presents %}
                                <ul class="timeline timeline-inverse">
                                    {% for present in presents %}
                                        <li class="time-label">
                                            <span class="bg-green">{{ present.date_event }}</span>
                                        </li>
                                        <li>
                                            <i class="fa fa-comments bg-yellow"></i>
                                            <div class="timeline-item">
                                                <span class="time"><i class="fa fa-clock-o">

                                                </i> 27 mins ago</span>

                                                <h3 class="timeline-header">
                                                    <a href="#">{{ present.date_event }}</a>
                                                    {{ present.event }} на должность.
                                                </h3>

                                                <div class="timeline-body">
                                                    Переведен на должность {{ present.position }}
                                                    в подразделение {{ present.division }}
                                                </div>
                                                <div class="timeline-footer">
                                                    <a class="btn btn-warning btn-flat btn-xs">Посмотреть</a>
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>

                            {% endif %}
                            <!-- The timeline -->
                        </div>
                        <!-- /.tab-pane -->

                        <div class="tab-pane" id="settings">

                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    {% endfor %}
{% endblock %}

templates/accountprofile/hse/listaccountprofile.html
{% extends 'adminlte/base.html' %}

{% block content %}
    {% load render_table from django_tables2 %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Штатная расстановка</h3>
                    <div class="group-btn pull-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                                aria-expanded="false">Действие
                            <span class="fa fa-caret-down"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'update_account' 'create_account' %}">Создать работника</a></li>
                        </ul>
                    </div>

                </div>
                <div class="box-body">
                    {% render_table table %}
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Footer
                </div>
                <!-- /.box-footer-->
            </div>
        </div>
    </div>
{% endblock %}